version: 2

project_name: ennacmd

builds:
  - id: ennacmd
    main: .
    binary: ennacmd
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    builds:
      - ennacmd
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    formats:
      - zip
    format_overrides:
      - goos: linux
        formats:
          - tar.gz
      - goos: darwin
        formats:
          - tar.gz

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'